-- 仪表盘定义表
CREATE TABLE sys_dashboard (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL COMMENT '仪表盘名称',
  description TEXT COMMENT '说明',
  layout_json TEXT NOT NULL COMMENT '布局和组件配置JSON',
  is_default INT DEFAULT 0 COMMENT '是否默认仪表盘',
  status INT DEFAULT 1 COMMENT '1=启用 0=禁用',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted INT DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
